### ISSUE TITLE
Java - Server Synchronization

### ISSUE THREAD

**Issue by MasterGrinch** [TeamA1-SPM/ProjektOrganisation#30]
#2 

- [x] get road from server
- [x] game activated by server countdown
- [x] draw enemy car #6
- [x] synchronize NPC cars #2 
- [x] end game screen #10
- [x] spielernamen #6  
- [x] highscore list #3
